#Database related properties
database.driver=com.mysql.cj.jdbc.Driver
database.url=jdbc:mysql://localhost:3306/db01312026
#spring.config.import=optional:file:.env[.properties]
#database.user=${DATABASE_USERNAME}
#database.password=${DATABASE_PASSWORD}
database.user=root
database.password=root

#Hibernate related properties
hibernate.dialect=org.hibernate.dialect.MySQL5Dialect
hibernate.show_sql=true
hibernate.format_sql=true
hibernate.hbm2ddl.auto=update
